stages:
  - prebuild
  - build
  - deploy
  - release

variables:
  IMAGE_TAG: mr-$CI_MERGE_REQUEST_IID-$CI_COMMIT_SHORT_SHA
  API_IMAGE_NAME: $INTERNAL_REGISTRY_URL/library/recipes:$IMAGE_TAG
  UI_IMAGE_NAME: $INTERNAL_REGISTRY_URL/library/recipes-ui:$IMAGE_TAG
  ARGO_CD_APP_REPO: gitlab.alexfricker.com/devops/gitops-dev.git
  KUSTOMIZATION_SOURCE_DIR: recipes
  KUSTOMIZATION_BACKEND_IMAGE_NAME: recipes-backend
  KUSTOMIZATION_FRONTEND_IMAGE_NAME: recipes-frontend
  ARGOCD_APP_NAME: recipes-dev

build-ui-files:
  stage: prebuild
  image: registry.apps.oc01.alexfricker.com/library/gitlab-runner:v.1.0.0
  script: |
    make env
    echo "VITE_SENTRY_ENVIRONMENT=dev" >> frontend/.env
    echo "VITE_SENTRY_RELEASE=dev" >> frontend/.env
    echo "VITE_SENTRY_DSN=\"$SENTRY_DSN_UI\"" >> frontend/.env
    npm --prefix=frontend run build
    ./.venv/bin/python3 manage.py collectstatic --noinput
  cache:
    key: env-cache
    paths:
      - frontend/node_modules
      - .venv
  artifacts:
    paths:
      - frontend/dist
      - staticfiles

include:
  - component: $CI_SERVER_FQDN/devops/gitlab-cicd/build-image@1.0.0
    inputs:
      image-name: $API_IMAGE_NAME
      job-name-suffix: api
  - component: $CI_SERVER_FQDN/devops/gitlab-cicd/build-image@1.0.0
    inputs:
      image-name: $UI_IMAGE_NAME
      job-name-suffix: ui
      dockerfile: Dockerfile.nginx
  - component: $CI_SERVER_FQDN/devops/gitlab-cicd/deploy-image@1.0.0
    inputs:
      job-name-suffix: openshift
      source-repo: $ARGO_CD_APP_REPO
      source-dir: $KUSTOMIZATION_SOURCE_DIR
      image-tags: "$KUSTOMIZATION_BACKEND_IMAGE_NAME=$IMAGE_TAG $KUSTOMIZATION_FRONTEND_IMAGE_NAME=$IMAGE_TAG"
  - component: $CI_SERVER_FQDN/devops/gitlab-cicd/release-image@1.0.0
    inputs:
      app-name: $ARGOCD_APP_NAME