stages:
  - prebuild
  - build
  - deploy
  - release

variables:
  IMAGE_TAG: v.$CI_COMMIT_TAG
  API_IMAGE_NAME: $INTERNAL_REGISTRY_URL/library/recipes:$IMAGE_TAG
  UI_IMAGE_NAME: $INTERNAL_REGISTRY_URL/library/recipes-ui:$IMAGE_TAG
  UI_DEMO_IMAGE_NAME: $INTERNAL_REGISTRY_URL/library/recipes-ui-demo:$IMAGE_TAG
  ARGO_CD_APP_REPO: gitlab.alexfricker.com/devops/gitops-prod.git
  ARGO_CD_DEMO_REPO: gitlab.alexfricker.com/devops/gitops-demo.git
  KUSTOMIZATION_SOURCE_DIR: recipes
  KUSTOMIZATION_BACKEND_IMAGE_NAME: recipes-backend
  KUSTOMIZATION_FRONTEND_IMAGE_NAME: recipes-frontend
  ARGOCD_APP_NAME: recipes-prod

build-ui-files:
  stage: prebuild
  image: registry.apps.oc01.alexfricker.com/library/gitlab-runner:v.1.0.0
  script: |
    make env
    echo "VITE_SENTRY_ENVIRONMENT=prod" >> frontend/.env
    echo "VITE_SENTRY_RELEASE=\"$IMAGE_TAG\"" >> frontend/.env
    echo "VITE_SENTRY_DSN=\"$SENTRY_DSN_UI\"" >> frontend/.env
    export SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN_UI
    npm --prefix=frontend run build
    ./.venv/bin/python3 manage.py collectstatic --noinput
  cache:
    key: env-cache
    paths:
      - frontend/node_modules
      - .venv
  artifacts:
    name: ui-prod
    paths:
      - frontend/dist
      - staticfiles

build-ui-files-demo:
  stage: prebuild
  image: registry.apps.oc01.alexfricker.com/library/gitlab-runner:v.1.0.0
  script: |
    make env
    echo "VITE_BASE_PATH=/demos/recipes/" >> frontend/.env
    echo "VITE_SENTRY_ENVIRONMENT=demo" >> frontend/.env
    echo "VITE_SENTRY_RELEASE=\"$IMAGE_TAG\"" >> frontend/.env
    echo "VITE_SENTRY_DSN=\"$SENTRY_DSN_UI\"" >> frontend/.env
    export SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN_UI
    npm --prefix=frontend run build
    ./.venv/bin/python3 manage.py collectstatic --noinput
  cache:
    key: env-cache
    paths:
      - frontend/node_modules
      - .venv
  artifacts:
    name: ui-demo
    paths:
      - frontend/dist
      - staticfiles

include:
  - component: $CI_SERVER_FQDN/devops/gitlab-cicd/build-image@1.0.0
    inputs:
      image-name: $UI_IMAGE_NAME
      job-name-suffix: ui-prod
      dockerfile: Dockerfile.nginx
  - component: $CI_SERVER_FQDN/devops/gitlab-cicd/build-image@1.0.0
    inputs:
      image-name: $UI_DEMO_IMAGE_NAME
      job-name-suffix: ui-demo
      dockerfile: Dockerfile.nginx
  - component: $CI_SERVER_FQDN/devops/gitlab-cicd/deploy-image@1.0.0
    inputs:
      job-name-suffix: openshift
      environment: production
      source-repo: $ARGO_CD_APP_REPO
      source-dir: $KUSTOMIZATION_SOURCE_DIR
      image-tags: "$KUSTOMIZATION_BACKEND_IMAGE_NAME=$IMAGE_TAG $KUSTOMIZATION_FRONTEND_IMAGE_NAME=$IMAGE_TAG"
  - component: $CI_SERVER_FQDN/devops/gitlab-cicd/deploy-image@1.0.0
    inputs:
      job-name-suffix: demo
      environment: production
      source-repo: $ARGO_CD_DEMO_REPO
      source-dir: $KUSTOMIZATION_SOURCE_DIR
      image-tags: "$KUSTOMIZATION_BACKEND_IMAGE_NAME=$IMAGE_TAG $KUSTOMIZATION_FRONTEND_IMAGE_NAME=$IMAGE_TAG"
  - component: $CI_SERVER_FQDN/devops/gitlab-cicd/release-image@1.0.0
    inputs:
      app-name: $ARGOCD_APP_NAME

# Override the generated build jobs to add dependencies
build-image-ui-prod:
  dependencies:
    - build-ui-files

build-image-ui-demo:
  dependencies:
    - build-ui-files-demo

build-image-api:
  stage: build
  image: 'quay.io/buildah/stable:latest'
  script: |
    export STORAGE_DRIVER=vfs

    buildah login \
      --username=${INTERNAL_REGISTRY_USERNAME} \
      --password=${INTERNAL_REGISTRY_PASSWORD} \
      ${INTERNAL_REGISTRY_URL}

    buildah --storage-driver=$STORAGE_DRIVER bud \
      -t "$API_IMAGE_NAME" \
      --build-arg SENTRY_RELEASE_VERSION=$IMAGE_TAG \
      .

    buildah push "$API_IMAGE_NAME"

create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script: echo "Creating release $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG of components in $CI_PROJECT_PATH"

create-sentry-release:
  stage: release
  image: registry.apps.oc01.alexfricker.com/library/gitlab-runner:v.1.0.0
  script:
    - curl -sL https://sentry.io/get-cli/ | bash
    - export SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN_UI
    - export SENTRY_ORG=sentry
    - export SENTRY_PROJECT=recipes-ui
    - sentry-cli --url https://sentry.alexfricker.com/ releases new "$IMAGE_TAG"
    - sentry-cli --url https://sentry.alexfricker.com/ releases set-commits "$IMAGE_TAG" --auto
    - sentry-cli --url https://sentry.alexfricker.com/ releases finalize "$IMAGE_TAG"
    - export SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN_API
    - export SENTRY_ORG=sentry
    - export SENTRY_PROJECT=recipes-django
    - sentry-cli --url https://sentry.alexfricker.com/ releases new "$IMAGE_TAG"
    - sentry-cli --url https://sentry.alexfricker.com/ releases set-commits "$IMAGE_TAG" --auto
    - sentry-cli --url https://sentry.alexfricker.com/ releases finalize "$IMAGE_TAG"