# Generated by Django 5.2.8 on 2025-12-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fdc_id", models.IntegerField(db_index=True, unique=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("Foundation", "Foundation"),
                            ("SR Legacy", "SR Legacy"),
                            ("Survey (FNDDS)", "Survey (FNDDS)"),
                            ("Branded", "Branded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=2000)),
                ("detail_fetch_date", models.DateTimeField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
