# Generated by Django 5.2.8 on 2025-12-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fdc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="brand_name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
