# Generated by Django 5.2.8 on 2025-12-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fdc", "0002_fooditem_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="error_count",
            field=models.IntegerField(default=0),
        ),
    ]
